server:
  port: ${PORT:${SERVER_PORT:0}}
#  port: 8082

spring:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3366/movie-dev
    username: usr-movie
    password: pwd-movie
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  zipkin:
    enabled: true
    base-url: http://localhost:9411

queue:
  rabbitmessage:
    title: Working

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      tracing:
        enabled: true
